name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      firestore:
        image: google/cloud-sdk:emulators
        ports:
          - 8080:8080
        options: >-
          --entrypoint "gcloud beta emulators firestore start --host-port=0.0.0.0:8080"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
        run: pytest
